backup-file:
	mv ./node_modules/metro/src/lib/createModuleIdFactory.js ./node_modules/metro/src/lib/createModuleIdFactory.js_bak
	mv ./node_modules/metro/src/DeltaBundler/Serializers/plainJSBundle.js ./node_modules/metro/src/DeltaBundler/Serializers/plainJSBundle.js_bak


copy-file:
	cp ../../packages/metro/src/lib/createModuleIdFactory.js ./node_modules/metro/src/lib/createModuleIdFactory.js
	cp ../../packages/metro/src/DeltaBundler/Serializers/plainJSBundle.js ./node_modules/metro/src/DeltaBundler/Serializers/plainJSBundle.js